# NumPy


In [1]:
import numpy as np

In [2]:
myarr= np.array([[3,4,5,6,7]],np.int8)


In [3]:
myarr

array([[3, 4, 5, 6, 7]], dtype=int8)

In [4]:
myarr[0,1]

np.int8(4)

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0,1]=55

In [8]:
myarr

array([[ 3, 55,  5,  6,  7]], dtype=int8)

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Array Creation : Conversion from Other python Structure

In [13]:
listarray =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarray.dtype

dtype('int64')

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [19]:
zeros=np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [23]:
rng =np.arange(14)

In [24]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
lspace=np.linspace(1,10,12)

In [26]:
lspace

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [27]:
lspace.dtype

dtype('float64')

In [30]:
lspaces=np.linspace(1,10,10)


In [31]:
lspaces

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
lspace=np.linspace(1,10,12)

In [35]:
emp=np.empty((3,3))

In [36]:
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
emp_like=np.empty_like(lspace)

In [38]:
emp_like


array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [39]:
ide=np.identity(5)

In [40]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
ide.shape

(5, 5)

In [50]:
ide1=ide.ravel()

In [51]:
ide1.shape

(25,)

In [52]:
for item in lspace.flat:
    print(item)

1.0
1.8181818181818183
2.6363636363636367
3.4545454545454546
4.272727272727273
5.090909090909091
5.909090909090909
6.7272727272727275
7.545454545454546
8.363636363636363
9.181818181818182
10.0
